### ISSUE TITLE
Let the user define the keybinding

### ISSUE THREAD

**Issue by sucrecacao** [alexherbo2/phantom.kak#3]
Let the user decide the keymapping instead of defining it. 

It make a bit more work on install, but less work if the default keymapping doesn't fit the user config or conflict with other plugins. 

Plus, if a user edit the plugin's source code, it create conflict when pulling code from the repo during a plugin's update.

**Comment by alexherbo2** [comment]
A bit hard for myself, because phantom.kak has a bunch of mappings.

I don’t like plugins adding mappings on their own, but to be pragmatic, requiring users to add all the mappings is quite an involvement.

We can wrap the mappings in a command and let users call the command: `phantom-add-mappings`.

We can also expose the mappings in a user mode, so they’re still very discoverable.

User will enter in the phantom mode and see all the commands, and can do something like that for direct access:

``` kak
map global normal f ': enter-user-mode phantom<ret>f'
```

We can also create end user commands for each key that was bound:

``` kak
define-command phantom-restore-and-consume -docstring 'Restore selections and consume register' %{
  phantom-restore
  phantom-clear
}
```

So they are easily mappable:

``` kak
map global normal f ': phantom-restore-and-consume<ret>'
```

We can also combine all the solutions.

**Comment by sucrecacao** [comment]
> A bit hard for myself, because phantom.kak has a bunch of mappings.
I don’t like plugins adding mappings on their own, but to be pragmatic, requiring users to add all the mappings is quite an involvement.

I disagree, if you put a mapping example in the readme it's just a copy-past away.

Also as I a user I want to have all my mapping in one place.
Lets say I forgot about phantom `<a-i>` mapping and want to remap `insert <a-i>` to whatever.If all my remapping are not in one file I'll have a hard time find why my remapping doesn't work

**Comment by sucrecacao** [comment]
user mode is a good option too

**Comment by alexherbo2** [comment]
I’ve added the following end user commands:

- `phantom-restore-and-consume`
- `phantom-iterate-selections`
- `phantom-iterate-next-selection`
- `phantom-iterate-previous-selection`

---

[`phantom.kak`]

``` kak
provide-module phantom %{
  define-command phantom-add-mappings -docstring 'Add phantom mappings' %{
    map global normal F ': phantom-append<ret>'
    map global normal f ': phantom-restore-and-consume<ret>'
    map global normal <a-f> ': phantom-clear<ret>'

    # Iterate phantom selections in insert mode.
    map global insert <a-i> '<esc>: phantom-iterate-selections<ret>i'
    map global insert <a-a> '<esc>: phantom-iterate-selections<ret>a'
    map global insert <a-n> '<esc>: phantom-iterate-next-selection<ret>i'
    map global insert <a-p> '<esc>: phantom-iterate-previous-selection<ret>i'
  }
}
```

[`phantom.kak`]: https://github.com/alexherbo2/phantom.kak/blob/master/rc/phantom.kak
